#!/usr/bin/env python3
"""
Turn a microWakeWord model (.tflite + .json manifest) into a C header the
firmware compiles in.

    python3 scripts/embed-model.py models/hola_olivia.json --use

writes firmware/src/models/<name>.h, and with --use also points
firmware/wake_words.h at it. The manifest's cutoff, window and arena size
travel with the model, so swapping wake words is one command.
"""
import json
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parent.parent
args = [a for a in sys.argv[1:] if not a.startswith("--")]
use = "--use" in sys.argv
manifest_path = pathlib.Path(args[0]).resolve()
manifest = json.loads(manifest_path.read_text())
micro = manifest["micro"]
model = (manifest_path.parent / manifest["model"]).read_bytes()

if micro.get("feature_step_size", 10) != 10:
    sys.exit("Only feature_step_size 10 is supported by the firmware.")

name = re.sub(r"[^a-z0-9]+", "_", manifest_path.stem.lower()).strip("_")
out = root / "firmware" / "src" / "models" / f"{name}.h"

rows = [", ".join(f"0x{b:02x}" for b in model[i : i + 16]) for i in range(0, len(model), 16)]
out.write_text(
    f"""#pragma once
// Generated by scripts/embed-model.py from models/{manifest_path.name} — do not edit.
// Wake word: {manifest["wake_word"]} ({", ".join(manifest.get("trained_languages", []))})

#include <stdint.h>
#include "../wake_word_model.h"

alignas(16) static const uint8_t {name}_tflite[] = {{
  {(","+chr(10)+"  ").join(rows)}
}};

static const WakeWordModel {name}_model = {{
  "{manifest["wake_word"]}",
  {name}_tflite,
  {round(micro["probability_cutoff"] * 255)},  // probability_cutoff {micro["probability_cutoff"]}
  {micro["sliding_window_size"]},
  {micro["tensor_arena_size"]},
}};
"""
)
print(f"{out.relative_to(root)}: {len(model)} bytes")

if use:
    (root / "firmware" / "wake_words.h").write_text(
        f"""#pragma once

/**
 * Which wake words the device listens for. Generated by
 * `python3 scripts/embed-model.py models/{manifest_path.name} --use`; see the
 * README's "Wake word" section to train or swap models.
 */

#include "src/models/{name}.h"

static const WakeWordModel* const WAKE_WORD_MODELS[] = {{&{name}_model}};
static constexpr size_t WAKE_WORD_MODEL_COUNT = sizeof(WAKE_WORD_MODELS) / sizeof(WAKE_WORD_MODELS[0]);

/** For the serial log. */
#define WAKE_WORD_NAMES "{manifest["wake_word"]}"
"""
    )
    print("firmware/wake_words.h now uses", name)
