#pragma once

/**
 * Which wake words the device listens for. Generated by
 * `python3 scripts/embed-model.py models/hola_olivia.json --use`; see the
 * README's "Wake word" section to train or swap models.
 */

#include "src/models/hola_olivia.h"

static const WakeWordModel* const WAKE_WORD_MODELS[] = {&hola_olivia_model};
static constexpr size_t WAKE_WORD_MODEL_COUNT = sizeof(WAKE_WORD_MODELS) / sizeof(WAKE_WORD_MODELS[0]);

/** For the serial log. */
#define WAKE_WORD_NAMES "Hola Olivia / Hi Olivia"
